{% set name = "ticcutils" %}
{% set version = "0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LanguageMachines/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5cdbe9141b1739a31267d50d25688e62970d455aac7285f8abfd1b8c177932e   # v0.22

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - ticcutils

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - autoconf-archive
    - automake
    - libtool
    - pkg-config
  host:
    - libtar
    - libxml2
    - icu
    - zlib
    - bzip2
  run:
    - libtar
    - libxml2
    - icu
    - zlib
    - bzip2

test:
  commands:
    - test -d ${PREFIX}/include/ticcutils  # [unix]
    - test -f ${PREFIX}/lib/libticcutils.a  # [unix]

about:
  home: https://github.com/LanguageMachines/ticcutils
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: A generic utility library shared by Tilburg centre for Cognition and Communication (TiCC) software
  dev_url: https://github.com/LanguageMachines/ticcutils

extra:
  recipe-maintainers:
    - egpbos
    - jvdzwaan
    - martinreynaert
