{% set name = "ticcutils" %}
{% set version = "0.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LanguageMachines/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1058bd4dc148ab51e9d7c899eedb610123b2d2821f0fea6e0158f0500e333be7   # v0.22

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - ticcutils

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - autoconf
    - autoconf-archive
    - automake
    - make
    - libtool
    - pkg-config
  host:
    - libtar
    - libxml2
    - icu
    - zlib
    - bzip2
  run:
    - libtar
    - libxml2
    - icu
    - zlib
    - bzip2

test:
  commands:
    - test -d ${PREFIX}/include/ticcutils  # [unix]
    - test -f ${PREFIX}/lib/libticcutils.a  # [unix]

about:
  home: https://github.com/LanguageMachines/ticcutils
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: A generic utility library shared by Tilburg centre for Cognition and Communication (TiCC) software
  dev_url: https://github.com/LanguageMachines/ticcutils

extra:
  recipe-maintainers:
    - egpbos
    - jvdzwaan
    - martinreynaert
